### ISSUE TITLE
Table of contents in `xetex.pdf` unable to paginate

### ISSUE THREAD

**Issue by muzimuzhi** [ascherer/web#24]
| <code>xetex.pdf</code> | <code>pdftex.pdf</code> |
|--------|--------|
| ToC unable to paginate | ToC paginates |
| ![image](https://github.com/ascherer/web/assets/6376638/4c98c802-6194-48ec-a5f8-b82ec784c8ea) | ![image](https://github.com/ascherer/web/assets/6376638/67fad0b5-e550-4c13-926d-3e719f0ae06d) |

**Comment by ascherer** [comment]
Funny that you bring this up. Just today I made notes to compare the tables-of-contents of

- TeX: Tending to **overflow** on one page of ToC
- Metafont: Fits snuggly on one page of ToC, without `\title{\MF}`
- pdfTeX: Note generic “**WEB** output” on _second_ page of ToC (see above)
- XeTeX: **Overflow** on one page (see above)
- HiTeX: **CWEB**, 3 pages of ToC _at the end_; indentations; short lines _flush left_; should be _centered_ to match **WEB** conventions
- MetaPost: **CWEB**, added `\title{\MP}` at top of one page of ToC; full `\pagewidth` wide

in conjunction with `pdfwebtocfront.tex` in [knuth-pdf](https://ctan.org/pkg/knuth-pdf).

**Comment by ascherer** [comment]
It started only yesterday: https://tug.org/pipermail/metapost/2024-May/003564.html ;o)

**Comment by ascherer** [comment]
The aim is to have a uniform layout for these ToCs _including_ the `\title{PROGRAM}` on top.

**Comment by ascherer** [comment]
After `makeall -f "tex mf pdftex xetex hitex mp" -npt pdftex` you can replace `xetex.toc` with `pdftex.toc` and rerun `xetex xetex` to get a two-page ToC. I have no clue what's different in the various preambles.

See also issue #25 for a broader picture.

**Comment by muzimuzhi** [comment]
`makeall -f "tex mf pdftex xetex hitex mp" -npt pdftex` only compiled `tex.tex` for me. I use a non-full TeX Live installation. Would that matter?

It seems the ToC in `tex.pdf` has a similar problem (maybe that's intentional behavior since there's no "Overfull \vbox" in loading `CONTENTS.tex`):
![image](https://github.com/ascherer/web/assets/6376638/85f61cff-83b9-4f01-b7f4-34319d133620)

`xetex.pdf` has more chapters so the problem is more visually obvious, as the last ToC entry "55. Index" is missing.

Since `xewebmac.tex` loads `webmac.tex` (if `\botofcontents` is undefined), the difference may come from the differences between `pdfwebmac.tex` and `webmac.tex`.

**Comment by ascherer** [comment]
> `makeall -f "tex mf pdftex xetex hitex mp" -npt pdftex` only compiled `tex.tex` for me. I use a non-full TeX Live installation. Would that matter?

In order to use the `makeall` script you need the [source tree for TeX Live](https://github.com/TeX-Live/texlive-source). (If you want to commit code, submit patches to [tex-k@tug.org](mailto:tex-k@tug.org).)

> It seems the ToC in `tex.pdf` has a similar problem

Yes, TeX's ToC is tight. It runs to two pages for [the TeX Live version](https://mirrors.ctan.org/info/knuth-pdf/tex/tex-changes.pdf).

> Since `xewebmac.tex` loads `webmac.tex` (if `\botofcontents` is undefined), the difference may come from the differences between `pdfwebmac.tex` and `webmac.tex`.

If you run `makeall -f tex -npt pdftex`, the outdated macros `xewebmac.tex` and `pdfwebmac.tex` are _not_ used, but the modern `pwebmac.tex`(and that's the only version of "PDF macros for **WEB**" I use).

**Comment by ascherer** [comment]
Another facet of this issue is that `tex-changes.pdf` has a two-page ToC and the main code starts on page **4** instead of **3**. Will have to adapt `pdfwebtocfront.tex`.

**Comment by ascherer** [comment]
The most recent [`pdfwebtocfront.tex`](https://github.com/ascherer/cwebbin/blob/cweb-4.12/texinputs/pdfwebtocfront.tex) addresses this issue: `\pdfpageheight` is increased by half an inch for the _long_ programs (TeX, Metafont, pdfTeX, and XeTeX). Also the default header title “**WEB** output” is replaced with “Table of Contents” on the second page of the ToC.

**Comment by ascherer** [comment]
Samples for the upcoming **knuth-pdf** package can be studied in [this release](https://github.com/ascherer/web/releases/tag/ctan-20240524).

**Comment by ascherer** [comment]
Home at last: https://ctan.org/tex-archive/info/knuth-pdf/xetex
